platform :ios, '9.3'

use_frameworks!

target 'LionheartOtherAppsViewController_Example' do
  pod 'LionheartOtherAppsViewController', :path => '../'

  target 'LionheartOtherAppsViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1'
    pod 'Nimble', '~> 7'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
