platform :ios, '9.3'

use_frameworks!

target 'LionheartOtherAppsViewController_Example' do
  pod 'LionheartOtherAppsViewController', :path => '../'

  target 'LionheartOtherAppsViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
