platform :ios, '15'

use_frameworks!

target 'LionheartOtherAppsViewController_Example' do
  pod 'LionheartOtherAppsViewController', :path => '../'

  target 'LionheartOtherAppsViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
